#!/usr/bin/env bash
#===============================================================================
# WHAT:    AUTO-tcx-remote-pair-gen.sh — the ONE writer of
#          ~/.config/i3minator/remote-<profile>.yml. One file per line of the
#          cockpit profiles file, so $mod+Ctrl+x lists "remote-<name>" next to
#          the local "<name>" launcher (type "remote-" in rofi to filter).
#
# WHY:     2026-10-02: the first remote-*.yml were hand-written, then patched
#          with an inline python regex. Hand edits drift; a generator from the
#          single source (profiles.conf) does not.
#
# INPUTS:  [PROFILE…]   only these profiles (default: every profile)
#          -n           dry run: print the YAML to stdout, write nothing
#          env TCX_COCKPIT_PROFILES_FILE (default ~/.config/tcx-cockpit/profiles.conf)
#              I3MINATOR_DIR             (default ~/.config/i3minator)
#
# OUTPUTS: remote-<p>.yml, written ATOMICALLY (temp file in the same dir, then
#          rename). Default workspace = the `workspace:` of the LOCAL twin
#          <p>.yml when it exists, else 1 (rofi asks and overrides anyway).
#          Each file is then checked with `i3minator validate`.
#          stdout: "gen<TAB>remote-<p><TAB>ok|FAIL<TAB>detail" per profile.
#          exit 0 all ok · 1 any validate failure · 64 usage/missing input
#
# RE-RUN SAFETY: idempotent — same profiles in, byte-identical files out.
#          Files are marked GENERATED; edit profiles.conf, never the YAML.
#===============================================================================
set -uo pipefail

HERE="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
WINDOW="$HERE/AUTO-create-or-reuse-and-enter-local-tmux-session-for-remote-twin.sh"
CONF="${TCX_COCKPIT_PROFILES_FILE:-$HOME/.config/tcx-cockpit/profiles.conf}"
OUT="${I3MINATOR_DIR:-$HOME/.config/i3minator}"
DRY=0
[[ "${1:-}" == "-n" ]] && { DRY=1; shift; }

for c in i3minator grep; do command -v "$c" >/dev/null || { echo "gen: missing $c" >&2; exit 64; }; done
[[ -r "$CONF" ]] || { echo "gen: profiles file not readable: $CONF" >&2; exit 64; }
[[ -x "$WINDOW" ]] || { echo "gen: window program not executable: $WINDOW" >&2; exit 64; }

mapfile -t NAMES < <(grep -v '^[[:space:]]*#' "$CONF" | grep -v '^[[:space:]]*$' | cut -d: -f1)
(( $# )) && NAMES=("$@")

render(){  # $1 profile  $2 worker  $3 session  $4 workspace  $5 local dir
local tags="[$1, remote, code, terminal]"
local launcher="$WINDOW"
if [[ "$1" == rag-papers-gcp-repo ]]; then
    # This profile's remote session was provisioned separately. A missing
    # remote is an error here; the i3 launcher must never create it implicitly.
    tags='[rag-papers-gcp-repo, rag-papers, gcp, remote, code, terminal]'
    launcher="$HERE/AUTO-create-and-attach-local-tmux-session-for-existing-remote-tmux-session.sh"
fi
if [[ "$1" == whatsapp-filters ]]; then
    tags='[whatsapp-filters, whatsapp, docs, remote, code, terminal]'
    launcher="$HERE/AUTO-tcx-remote-pair-window.sh"
fi
cat <<EOF
# GENERATED by $HERE/AUTO-tcx-remote-pair-gen.sh — do not edit.
# Source: $CONF line "$1". Edit that line, then re-run the generator.
#
# Remote twin of "$1": remote claude in session "$3" on worker "$2", plus the
# local tmux session remote-$1 (cockpit, Codex manager, shell). Trigger: \$mod+Ctrl+x, type
# "remote-". The workspace below is only a default; rofi asks.
name: remote-$1
workspace: $4
layout: splith
describe: remote-$1
panes:
  - cmd: wezterm start --always-new-process --class i3minator-remote-$1 --cwd $5 -- $launcher $1
    match: { class: "^i3minator-remote-$1\$" }
    tags: $tags
EOF
}

rc=0
for p in "${NAMES[@]}"; do
    line="$(grep -v '^[[:space:]]*#' "$CONF" | grep -m1 "^${p}:")" \
        || { printf 'gen\tremote-%s\tFAIL\tno profile line\n' "$p"; rc=1; continue; }
    IFS=':' read -r _ w s _ <<<"$line"
    ws="$(grep -m1 -E '^workspace:[[:space:]]*[0-9]+' "$OUT/$p.yml" 2>/dev/null | grep -oE '[0-9]+')"
    ws="${ws:-1}"
    local_dir="$(awk -F'\t' -v name="$p" '$1==name{print $2; exit}' "${TCX_LOCAL_DIRS:-$HOME/.config/tcx-cockpit/local-dirs.tsv}" 2>/dev/null)"
    [[ -d "$local_dir" ]] || local_dir="$HOME"
    if (( DRY )); then render "$p" "$w" "$s" "$ws" "$local_dir"; echo "---"; continue; fi
    tmp="$(mktemp "$OUT/.remote-$p.yml.XXXXXX")"
    render "$p" "$w" "$s" "$ws" "$local_dir" > "$tmp" && chmod 644 "$tmp" && mv -f "$tmp" "$OUT/remote-$p.yml"
    if v="$(i3minator validate "remote-$p" 2>&1)"; then printf 'gen\tremote-%s\tok\tworker=%s ws=%s\n' "$p" "$w" "$ws"
    else printf 'gen\tremote-%s\tFAIL\t%s\n' "$p" "$v"; rc=1; fi
done
exit $rc
